### ISSUE TITLE
Enabling verbose mode crashes cyflash

### ISSUE THREAD

**Issue by anuraj-rp** [arachnidlabs/cyflash#28] opened 2019-08-14 13:07 UTC
Hi,

When I enable the --verbose mode, cyflash crashes with the following traceback

```
Traceback (most recent call last):
File "..\Scripts\cyflash-script.py", line 11, in <module>
load_entry_point('cyflash==1.7', 'console_scripts', 'cyflash')()
File "..\lib\site-packages\cyflash\bootload.py", line 396, in main
    args.psoc5)
File "..\lib\site-packages\cyflash\bootload.py", line 254, in bootload
    self.enter_bootloader(data)
File "..\lib\site-packages\cyflash\bootload.py", line 304, in enter_bootloader
    silicon_id, silicon_rev, bootloader_version = self.session.enter_bootloader(self.key)
File "..\lib\site-packages\cyflash\protocol.py", line 388, in enter_bootloader
    response = self.send(EnterBootloaderCommand(key))
File "..\lib\site-packages\cyflash\protocol.py", line 380, in send
    self.transport.send(packet)
File "..\lib\site-packages\cyflash\protocol.py", line 432, in send
    print("s: 0x%02x" % ord(char))
TypeError: ord() expected string of length 1, but int found
```
Is this a known problem?

**Comment by C47D** [comment] 2019-08-14 14:05
It's been a lot since i tried to use this module, what python version are you using?

**Comment by anuraj-rp** [comment] 2019-08-15 05:32
I am using python version 3.7.2 on a 64 bit Windows 10 machine.

**Comment by C47D** [comment] 2019-08-17 19:53
I'm not very fluent in Python, but this is what i guess the problem is:

This is the method where the error comes from (it's part of the SerialTransport class):
```python
    def send(self, data):
        if self._verbose:
            for char in data:
                print("s: 0x%02x" % ord(char))
        self.f.write(data)
```

So with `verbose` set to `True` the elements of `data` gets printed on the console, based on this question on StackOverflow ([TypeError: ord() expected string of length 1, but int found](https://stackoverflow.com/questions/19897209/troubleshooting-typeerror-ord-expected-string-of-length-1-but-int-found)) I'm guessing in Python 3.7.2 it's not neccesary to call ord(), so `print("s: 0x%02x" % char)` would be enough.

**Comment by anuraj-rp** [comment] 2019-08-19 05:47
Hi,

I don't see this change on your fork. 

Is the code in previous comment the complete diff patch file?

**Comment by anuraj-rp** [comment] 2019-08-19 07:49
Hi,

I tried your code in Python3 and it works but it fails in Python2 with the following error.

```
TypeError: %x format: a number is required, not str
```

Ofcourse we could fix this by various methods mentioned in the Stackoverflow link
[Python 2 and 3 compatible method to convert bytes to integer
](https://stackoverflow.com/questions/26121553/python-2-and-3-compatible-method-to-convert-bytes-to-integer)

Python2 reaches end of life on 1st, Jan, 2020. Is there a plan to keep this compatible with Python2?

**Comment by C47D** [comment] 2019-08-19 13:41
> Hi,
I don't see this change on your fork.
Is the code in previous comment the complete diff patch file?

It's on my machine, I forgot to push it on my fork.

> Python2 reaches end of life on 1st, Jan, 2020. Is there a plan to keep this module compatible with Python2?

I was also thinking about this, maybe @jsiverskog can let us know about his plans.

**Comment by jsiverskog** [comment] 2019-08-19 17:02
how about something like this:
```
for part in bytearray(data, encoding="ascii"):
    print("r: 0x%02x" % part)
```

**Comment by anuraj-rp** [comment] 2019-08-20 07:58
Hi,

It works without the encoding part in the code from @jsiverskog 
ascii only allows values upt 255. 

I created a pull request with the fix. Tested with Python3.7.2 and Python2.7.15 on Windows 10 64 bit machine

**Comment by anuraj-rp** [comment] 2019-08-21 09:22
Should I close this issue? @C47D @jsiverskog

**Comment by C47D** [comment] 2019-08-21 13:41
You can close it now or until your pull request gets merged.

**Closed** 2019-08-21 18:52 UTC
